In [55]:
import pandas as pd
import numpy as np

In [56]:
data = pd.read_csv('SPY.csv')
pd.set_option('display.max_columns', None)
data

,Unnamed: 0,Track,Album Name,Artist,Release Date,ISRC,All Time Rank,Track Score,Spotify Streams,Spotify Playlist Count,Spotify Playlist Reach,Spotify Popularity,YouTube Views,YouTube Likes,TikTok Posts,TikTok Likes,TikTok Views,YouTube Playlist Reach,Apple Music Playlist Count,AirPlay Spins,SiriusXM Spins,Deezer Playlist Count,Deezer Playlist Reach,Amazon Playlist Count,Pandora Streams,Pandora Track Stations,Soundcloud Streams,Shazam Counts,TIDAL Popularity,Explicit Track
0,0,MILLION DOLLAR BABY,Million Dollar Baby - Single,Tommy Richman,4/26/2024,QM24S2402528,1,725.4,"390,470,936","30,716","196,631,588",92.0,"84,274,754","1,713,126","5,767,700","651,565,900","5,332,281,936","150,597,040",210.0,"40,975",684,62.0,"17,598,718",114.0,"18,004,655","22,931","4,818,457","2,669,262",-,0.000000
1,1,Not Like Us,Not Like Us,Kendrick Lamar,5/4/2024,USUG12400910,2,545.9,"323,703,884","28,113","174,597,137",92.0,"116,347,040","3,486,739","674,700","35,223,547","208,339,025","156,380,351",188.0,"40,778",3,67.0,"10,422,430",111.0,"7,780,028","28,444","6,623,075","1,118,279",NaN,1.000000
2,2,i like the way you kiss me,I like the way you kiss me,Artemas,3/19/2024,QZJ842400387,3,538.4,"601,309,283","54,331","211,607,669",92.0,"122,599,116","2,228,730","3,025,400","275,154,237","3,369,120,610","373,784,955",-inf,"74,333",536,136.0,"36,321,847",172.0,"5,022,621","5,639","7,208,651","5,285,340",NaN,0.000000
3,3,Flowers,Flowers - Single,Miley Cyrus,1/12/2023,USSM12209777,4,444.9,"2,031,280,633","269,802","136,569,078",NaN,"1,096,100,899","10,629,796","7,189,811","1,078,757,968","14,603,725,994","3,351,188,582",394.0,"1,474,799","2,182",264.0,"24,684,248",210.0,"190,260,277","203,384",NaN,"11,822,942",NaN,0.000000
4,4,Houdini,Houdini,Eminem,5/31/2024,USUG12403398,5,423.3,"107,034,922","7,223","151,469,874",88.0,"77,373,957","3,670,188","16,400",inf,NaN,"112,763,851",182.0,"12,185",1,NaN,"17,660,624",105.0,"4,493,884","7,006","207,179","457,017",NaN,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6868,6868,Lean On (feat. Mï¿½ï¿½ & DJ Snake) - J Balvin ...,Lean On (feat. Mï¿½ï¿½ & DJ Snake) [J Balvin &...,Major Lazer,9/4/2015,FR6P11501180,"1,030",47.396160416820784,"53,822,187","2,081","465,455",NaN,"3,617,929,617","17,418,989",NaN,37,956,"1,393,748,323",NaN,NaN,-,1.005055116904699,234,NaN,NaN,-,NaN,NaN,NaN,-0.034493
6869,6869,Is It Over Now? (Taylor's Version) (From The V...,1989 (Taylor's Version),Taylor Swift,10/26/2023,USUG12306691,240,100.18066368348285,"406,821,432","20,404","26,073,555",NaN,"23,505,530","266,969","80,218","12,641,848","113,073,762","1,569,274,837",38.00539590588506,"337,262",20,26.997652078774916,"740,249",37.99079084751558,"18,715,607","6,762",NaN,"1,551,811",NaN,0.003324
6870,6870,You,You,Willy Paul,11/25/2022,QZW9K2296922,"4,546",19.50127396224503,"330,280",174,"8,772",19.99422238969727,"6,023,690","52,656","1,700,000","19,786,116","267,911,446",NaN,-inf,NaN,NaN,inf,-inf,inf,-,inf,-,"184,355",NaN,0.011949
6871,6871,To the Bone,Flying Solo,Pamungkas,6/14/2019,FR2X41995983,"4,221",20.468227375728517,"442,614,126","39,861","12,416,351",72.00612559020607,"461,577,619","2,914,234","912,650","149,476,116","1,424,731,067","45,212,529",10.014911093041839,"3,292",NaN,-inf,NaN,NaN,NaN,NaN,NaN,"403,782",NaN,-0.014058
6872,6872,i love you,"WHEN WE ALL FALL ASLEEP, WHERE DO WE GO?",Billie Eilish,3/29/2019,USUM71900773,"2,390",29.18645627610385,"930,343,185","116,055","42,732,119",inf,"280,579,630","3,517,952","451,642","85,881,445","724,117,161","128,657,658",inf,621,1,35.99953841612304,"606,884",25.993409714943493,"38,736,042","167,546","3,706,611","2,035,027",NaN,0.011580

In [57]:
data_info = pd.DataFrame()

data_info['null'] = data.isnull().sum()
data_info['Tipe'] = data.dtypes
data_info['Unik'] = data.nunique()

data_info = data_info[data_info['null'] > 0]

data_info['Persentase Null'] = (data_info['null'] / len(data)) * 100
data_info.sort_values(by='Persentase Null', ascending=False, inplace=True)

data_info

                            null    Tipe  Unik  Persentase Null
TIDAL Popularity            4004  object     3        58.256947
Soundcloud Streams          2894  object  1268        42.106795
SiriusXM Spins              1835  object   692        26.698676
Amazon Playlist Count       1532  object  1537        22.290121
Deezer Playlist Count       1450  object  1697        21.097046
Spotify Popularity          1372  object  1595        19.962171
Apple Music Playlist Count  1202  object  1893        17.488724
Pandora Track Stations      1105  object  2978        16.077404
TikTok Posts                1012  object  3321        14.724283
Pandora Streams              956  object  3494        13.909501
TikTok Views                 882  object  3619        12.832824
YouTube Playlist Reach       875  object  3461        12.730976
TikTok Likes                 839  object  3618        12.207188
Deezer Playlist Reach        792  object  3561        11.523352
Track Score                  784  object  2611        11.406955
Shazam Counts                510  object  4005         7.420340
AirPlay Spins                418  object  3270         6.081769
YouTube Likes                283  object  4286         4.117561
YouTube Views                271  object  4293         3.942965
Spotify Streams               92  object  4428         1.338571
Spotify Playlist Reach        65  object  4481         0.945730
Spotify Playlist Count        56  object  4210         0.814782
Artist                         3  object  2001         0.043649

In [58]:
data = data.drop(['Unnamed: 0', 'TIDAL Popularity', 'Release Date', 'ISRC', 'Track', 'Album Name', 'Artist', 'Soundcloud Streams'], axis=1)

In [59]:
data = data.replace(',', '', regex=True)

In [60]:
data = data.replace(['inf', '-inf', '-'], np.nan)

In [61]:
data = data.apply(pd.to_numeric, errors='coerce')

In [62]:
data

,All Time Rank,Track Score,Spotify Streams,Spotify Playlist Count,Spotify Playlist Reach,Spotify Popularity,YouTube Views,YouTube Likes,TikTok Posts,TikTok Likes,TikTok Views,YouTube Playlist Reach,Apple Music Playlist Count,AirPlay Spins,SiriusXM Spins,Deezer Playlist Count,Deezer Playlist Reach,Amazon Playlist Count,Pandora Streams,Pandora Track Stations,Shazam Counts,Explicit Track
0,1,725.400000,3.904709e+08,30716.0,196631588.0,92.000000,8.427475e+07,1713126.0,5767700.0,6.515659e+08,5.332282e+09,1.505970e+08,210.000000,40975.0,684.0,62.000000,17598718.0,114.000000,18004655.0,22931.0,2669262.0,0.000000
1,2,545.900000,3.237039e+08,28113.0,174597137.0,92.000000,1.163470e+08,3486739.0,674700.0,3.522355e+07,2.083390e+08,1.563804e+08,188.000000,40778.0,3.0,67.000000,10422430.0,111.000000,7780028.0,28444.0,1118279.0,1.000000
2,3,538.400000,6.013093e+08,54331.0,211607669.0,92.000000,1.225991e+08,2228730.0,3025400.0,2.751542e+08,3.369121e+09,3.737850e+08,NaN,74333.0,536.0,136.000000,36321847.0,172.000000,5022621.0,5639.0,5285340.0,0.000000
3,4,444.900000,2.031281e+09,269802.0,136569078.0,NaN,1.096101e+09,10629796.0,7189811.0,1.078758e+09,1.460373e+10,3.351189e+09,394.000000,1474799.0,2182.0,264.000000,24684248.0,210.000000,190260277.0,203384.0,11822942.0,0.000000
4,5,423.300000,1.070349e+08,7223.0,151469874.0,88.000000,7.737396e+07,3670188.0,16400.0,NaN,NaN,1.127639e+08,182.000000,12185.0,1.0,NaN,17660624.0,105.000000,4493884.0,7006.0,457017.0,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6868,1030,47.396160,5.382219e+07,2081.0,465455.0,NaN,3.617930e+09,17418989.0,NaN,3.700000e+01,9.560000e+02,1.393748e+09,NaN,NaN,NaN,1.005055,234.0,NaN,NaN,NaN,NaN,-0.034493
6869,240,100.180664,4.068214e+08,20404.0,26073555.0,NaN,2.350553e+07,266969.0,80218.0,1.264185e+07,1.130738e+08,1.569275e+09,38.005396,337262.0,20.0,26.997652,740249.0,37.990791,18715607.0,6762.0,1551811.0,0.003324
6870,4546,19.501274,3.302800e+05,174.0,8772.0,19.994222,6.023690e+06,52656.0,1700000.0,1.978612e+07,2.679114e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,184355.0,0.011949
6871,4221,20.468227,4.426141e+08,39861.0,12416351.0,72.006126,4.615776e+08,2914234.0,912650.0,1.494761e+08,1.424731e+09,4.521253e+07,10.014911,3292.0,NaN,NaN,NaN,NaN,NaN,NaN,403782.0,-0.014058
6872,2390,29.186456,9.303432e+08,116055.0,42732119.0,NaN,2.805796e+08,3517952.0,451642.0,8.588144e+07,7.241172e+08,1.286577e+08,NaN,621.0,1.0,35.999538,606884.0,25.993410,38736042.0,167546.0,2035027.0,0.011580

In [63]:
data['All Time Rank'].isnull().sum()

0

In [64]:
data = data.apply(lambda x: x.fillna(x.mean()), axis=0)

In [65]:
Q1 = data['All Time Rank'].quantile(0.25)
Q3 = data['All Time Rank'].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outliers = (data['All Time Rank'] < lower_bound) | (data['All Time Rank'] > upper_bound)
data = data[~outliers]

In [66]:
from sklearn.preprocessing import MinMaxScaler

columns_to_normalize = data.columns.difference(['All Time Rank'])

scaler = MinMaxScaler()
data[columns_to_normalize] = scaler.fit_transform(data[columns_to_normalize])

In [67]:
data.isnull().sum()

All Time Rank                 0
Track Score                   0
Spotify Streams               0
Spotify Playlist Count        0
Spotify Playlist Reach        0
Spotify Popularity            0
YouTube Views                 0
YouTube Likes                 0
TikTok Posts                  0
TikTok Likes                  0
TikTok Views                  0
YouTube Playlist Reach        0
Apple Music Playlist Count    0
AirPlay Spins                 0
SiriusXM Spins                0
Deezer Playlist Count         0
Deezer Playlist Reach         0
Amazon Playlist Count         0
Pandora Streams               0
Pandora Track Stations        0
Shazam Counts                 0
Explicit Track                0
dtype: int64

In [68]:
data

,All Time Rank,Track Score,Spotify Streams,Spotify Playlist Count,Spotify Playlist Reach,Spotify Popularity,YouTube Views,YouTube Likes,TikTok Posts,TikTok Likes,TikTok Views,YouTube Playlist Reach,Apple Music Playlist Count,AirPlay Spins,SiriusXM Spins,Deezer Playlist Count,Deezer Playlist Reach,Amazon Playlist Count,Pandora Streams,Pandora Track Stations,Shazam Counts,Explicit Track
0,1,1.000000,0.091200,0.052025,0.749520,0.957903,0.005163,0.027493,0.134445,2.775665e-02,2.286254e-02,0.020659,0.360370,0.023047,0.096238,0.096704,0.365135,0.540723,0.012301,0.006065,0.012144,0.032658
1,2,0.745756,0.075606,0.047616,0.665529,0.957903,0.007128,0.055956,0.015727,1.500520e-03,8.932682e-04,0.021452,0.322440,0.022937,0.000282,0.104628,0.216243,0.526371,0.005316,0.007524,0.005088,0.970498
2,3,0.735133,0.140444,0.092024,0.806606,0.957903,0.007511,0.035767,0.070522,1.172155e-02,1.444534e-02,0.051276,0.091205,0.041811,0.075384,0.213974,0.753599,0.818203,0.003432,0.001491,0.024047,0.032658
3,4,0.602699,0.474435,0.456987,0.520574,0.658442,0.067152,0.170592,0.167595,4.595500e-02,6.261451e-02,0.459715,0.677599,0.829559,0.307313,0.416819,0.512144,1.000000,0.129993,0.053798,0.053791,0.032658
4,5,0.572105,0.024999,0.012233,0.577373,0.915806,0.004740,0.058901,0.000382,4.933618e-03,5.119019e-03,0.015469,0.312096,0.006853,0.000000,0.049667,0.366419,0.497666,0.003070,0.001853,0.002079,0.970498
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6868,1030,0.039673,0.012571,0.003523,0.001774,0.658442,0.221649,0.279548,0.022442,1.448397e-09,4.017454e-09,0.191194,0.091205,0.030084,0.035141,0.000043,0.000005,0.114989,0.057049,0.023100,0.011599,0.000310
6869,240,0.114438,0.095019,0.034558,0.099387,0.658442,0.001440,0.004284,0.001870,5.385416e-04,4.848117e-04,0.215273,0.063839,0.189706,0.002677,0.041235,0.015359,0.177085,0.012787,0.001788,0.007060,0.035776
6870,4546,0.000163,0.000077,0.000293,0.000033,0.200100,0.000369,0.000845,0.039627,8.428868e-04,1.148689e-03,0.045714,0.091205,0.030084,0.035141,0.049667,0.027212,0.114989,0.057049,0.023100,0.000839,0.043865
6871,4221,0.001533,0.103379,0.067515,0.047329,0.747484,0.028278,0.046769,0.021274,6.367670e-03,6.108635e-03,0.006202,0.015582,0.001851,0.035141,0.049667,0.027212,0.114989,0.057049,0.023100,0.001837,0.019474
6872,2390,0.013881,0.217295,0.196571,0.162886,0.658442,0.017189,0.056457,0.010528,3.658542e-03,3.104703e-03,0.017649,0.091205,0.000349,0.000000,0.055500,0.012591,0.119688,0.026466,0.044318,0.009259,0.043518

In [69]:
data = data.drop_duplicates()

In [70]:
data.duplicated().sum()

0

In [71]:
data.to_csv('SPY_Clean.csv', index=False)